In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
X = np.arange(10).reshape(-1,1)
y = np.array([0,1,1,0,0,0,1,1,0,1])

In [4]:
X,y

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([0, 1, 1, 0, 0, 0, 1, 1, 0, 1]))

In [21]:
model = LogisticRegression(solver = 'liblinear', C= 10.0, random_state = 0)

In [22]:
model.fit(X,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [23]:
model.coef_

array([[0.11180522]])

In [24]:
model.intercept_

array([-0.4832956])

In [25]:
y_pred = model.predict(X)
p_pred = model.predict_proba(X)

In [26]:
y_pred, p_pred

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),
 array([[0.61852578, 0.38147422],
        [0.59181906, 0.40818094],
        [0.56455889, 0.43544111],
        [0.53690276, 0.46309724],
        [0.5090177 , 0.4909823 ],
        [0.48107642, 0.51892358],
        [0.45325299, 0.54674701],
        [0.4257186 , 0.5742814 ],
        [0.39863732, 0.60136268],
        [0.37216236, 0.62783764]]))

In [27]:
score = model.score(X,y)

In [28]:
score

0.6

In [32]:
# confusion matrix
confu = confusion_matrix(y, y_pred)

In [33]:
confu

array([[3, 2],
       [2, 3]])

In [34]:
report = classification_report(y, y_pred)

In [35]:
report

'              precision    recall  f1-score   support\n\n           0       0.60      0.60      0.60         5\n           1       0.60      0.60      0.60         5\n\n    accuracy                           0.60        10\n   macro avg       0.60      0.60      0.60        10\nweighted avg       0.60      0.60      0.60        10\n'